version: '3.3'

services:
  db:
    image: mysql:8.0.21
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: enjoyit_db
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_PASSWORD: rootroot

  sample:
    depends_on:
      - db
    image: astefanov1415/joinme:v1
    ports:
      - "8080:8080"
